# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[build]
# tokio-console needs this
rustflags = ["--cfg", "tokio_unstable"]

[target.aarch64-unknown-linux-gnu]
    rustflags = ["-C", "target-feature=+fp16"]
